### ISSUE TITLE
Error On yarn install

### ISSUE THREAD

**Issue by dustinwloring1988** [IceWhaleTech/CasaOS-UI#35]
I tried to the command "yarn install" and got the following error. I then tried "yarn lint" and got the following error. Am I doing something wrong. Before running the commands I did install yarn using "sudo apt install yarn"

Error - yarn install:
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

Error - yarn lint
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'lint'

**Comment by jerrykuku** [comment]
I think you should run it in the CasaOL-UI folder. Make sure you have git clone all the source code.
